=== jpinto7/tfm-support-files/ontologies-schema/scmevent.json
{
  "properties": {
    "assetId": {
      "type": "string"
    },
    "portalId": {
      "type": "string"
    },
    "eventType": {
      "type": "string"
    },
    "assetData": {
      "properties": {
        "temperature": {
          "type": "number"
        },
        "humidity": {
          "type": "number"
        },
        "weight": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "gatewayIP": {
      "type": "string"
    },
    "timestamp": {
      "type": "object",
      "required": [
        "$date"
      ],
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "location": {
      "type": "object",
      "required": [
        "coordinates",
        "type"
      ],
      "properties": {
        "coordinates": {
          "type": "array",
          "items": [{
              "type": "number",
              "maximum": 180,
              "minimum": -180
            },
            {
              "type": "number",
              "maximum": 90,
              "minimum": -90
            }
          ],
          "minItems": 2,
          "maxItems": 2
        },
        "type": {
          "type": "string",
          "enum": [
            "Point"
          ]
        }
      },
      "additionalProperties": false
    }
  },
  "type": "object",
  "description": "Info SCMEvent",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "SCMEvent",
  "additionalProperties": true,
  "required": [
    "assetId",
    "portalId",
    "timestamp",
    "location"
  ]
}

=== jpinto7/tfm-support-files/ontologies-schema/example-scmevent.json
{
    "assetId": "21CE442E",
    "portalId": "XVDTBJLP",
    "eventType": "ownership",
    "assetData": {
        "temperature": 0.83,
        "humidity": 55.2,
        "weight": 24.61
    },
    "timestamp": {
    	"$date": "2018-10-11T00:42:50.706Z"
    },
    "gatewayIP": "190.56.74.13",
    "location": {
        "type": "Point",
        "coordinates": [
            -90.5199,
            14.6328
        ]
    }
}
